// Data default awal sistem - Standalone / Hostinger Mode
export const INITIAL_SURAT_TUGAS = [
  {
    "id": "SPS-210637-1-79",
    "nomor": null,
    "noAgenda": "01063PK26",
    "agenda": "01063PK26",
    "namaKapal": "JURU LAS PT.YJS",
    "pemohon": "PT.YANI JAYA SUKSES",
    "docType": "SPS",
    "isSps": true,
    "isPds": false,
    "perihal": "DINAS SURVEY KLAS",
    "jenisSurvey": "MATKOM",
    "petugas": "ALFIAN BONE PUTRA",
    "pangkat": "",
    "jabatan": "SURVEYOR",
    "tempatSurvey": "DESA KAPOR",
    "lokasi": "DESA KAPOR",
    "tglMulai": "2026-08-01",
    "tglSelesai": "2026-08-01",
    "saranaTransportasi": "",
    "kategoriTransportasi": "",
    "kategoriPerjalanan": "",
    "status": "Menunggu Survei",
    "approvalStatus": "Menunggu ACC",
    "approvalDate": null,
    "approvedBy": null,
    "tarifDasar": 0,
    "uangHarian": 0,
    "biayaTiket": 0,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "jumlahEstimasi": 0,
    "isCito": false,
    "catatan": "",
    "shipsList": [
      {
        "noAgenda": "01063PK26",
        "namaKapal": "JURU LAS PT.YJS"
      }
    ],
    "shipsDetail": [],
    "isParafSent": false
  },
  {
    "id": "SPS-496204-1-21",
    "nomor": null,
    "noAgenda": "01062PK26",
    "agenda": "01062PK26",
    "namaKapal": "TERATAI MERAH II",
    "pemohon": "PELAYARAN CAHAYA LINTAS SAMUDERA",
    "docType": "SPS",
    "isSps": true,
    "isPds": false,
    "perihal": "DINAS SURVEY KLAS",
    "jenisSurvey": "TAHUNAN, TAHUNAN LL",
    "petugas": "ALFIAN BONE PUTRA",
    "pangkat": "",
    "jabatan": "SURVEYOR",
    "tempatSurvey": "DESA KAPOR",
    "lokasi": "DESA KAPOR",
    "tglMulai": "2026-09-03",
    "tglSelesai": "2026-09-03",
    "saranaTransportasi": "",
    "kategoriTransportasi": "",
    "kategoriPerjalanan": "",
    "status": "Menunggu Survei",
    "approvalStatus": "Menunggu ACC",
    "approvalDate": null,
    "approvedBy": null,
    "tarifDasar": 0,
    "uangHarian": 0,
    "biayaTiket": 0,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "jumlahEstimasi": 0,
    "isCito": false,
    "catatan": "",
    "shipsList": [
      {
        "noAgenda": "01062PK26",
        "namaKapal": "TERATAI MERAH II"
      }
    ],
    "shipsDetail": [],
    "isParafSent": false
  },
  {
    "id": "SPS-285755-1-60",
    "nomor": null,
    "noAgenda": "01061PK26",
    "agenda": "01061PK26",
    "namaKapal": "KERUK 6",
    "pemohon": "PT. BERLIAN KERUKTAMA INDONESIA",
    "docType": "SPS",
    "isSps": true,
    "isPds": false,
    "perihal": "DINAS SURVEY KLAS",
    "jenisSurvey": "TAHUNAN, TAHUNAN LL",
    "petugas": "ANDRE GUNTUR",
    "pangkat": "",
    "jabatan": "SURVEYOR",
    "tempatSurvey": "DESA KAPOR",
    "lokasi": "DESA KAPOR",
    "tglMulai": "2026-09-03",
    "tglSelesai": "2026-09-03",
    "saranaTransportasi": "",
    "kategoriTransportasi": "",
    "kategoriPerjalanan": "",
    "status": "Menunggu Survei",
    "approvalStatus": "Menunggu ACC",
    "approvalDate": null,
    "approvedBy": null,
    "tarifDasar": 0,
    "uangHarian": 0,
    "biayaTiket": 0,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "jumlahEstimasi": 0,
    "isCito": false,
    "catatan": "",
    "shipsList": [
      {
        "noAgenda": "01061PK26",
        "namaKapal": "KERUK 6"
      }
    ],
    "shipsDetail": [],
    "isParafSent": false
  },
  {
    "id": "ST-BKI-2026-001",
    "nomor": "A 0    /SV.245/PK/KI-26",
    "noAgenda": "001/2026",
    "agenda": "001/2026",
    "namaKapal": "KM MUTIARA LAUT",
    "pemohon": "PT. PELAYARAN NUSANTARA",
    "docType": "PDS",
    "isSps": false,
    "isPds": true,
    "perihal": "DINAS SURVEY KLAS",
    "jenisSurvey": "Annual Survey",
    "petugas": "ALFIAN BONE PUTRA",
    "pangkat": "GRADE 6 A",
    "jabatan": "SURVEYOR",
    "tempatSurvey": "PONTIANAK",
    "lokasi": "PONTIANAK",
    "tglMulai": "2026-08-01",
    "tglSelesai": "2026-08-03",
    "saranaTransportasi": "DARAT DAN AIR",
    "kategoriTransportasi": "Kendaraan Operasional",
    "kategoriPerjalanan": "Dalam Kota",
    "status": "Selesai",
    "approvalStatus": "ACC",
    "approvalDate": "2026-08-03T10:00:00+00:00",
    "approvedBy": "MUHSON NURROCHMAT",
    "tarifDasar": 3000000,
    "uangHarian": 0,
    "biayaTiket": 0,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "jumlahEstimasi": 3000000,
    "isCito": false,
    "catatan": "Annual Survey KM Mutiara Laut Pontianak. Selesai dan disetujui.",
    "shipsList": [],
    "shipsDetail": [],
    "isParafSent": false
  },
  {
    "id": "ST-BKI-2026-002",
    "nomor": "A 0    /SV.246/PK/KI-26",
    "noAgenda": "002/2026",
    "agenda": "002/2026",
    "namaKapal": "TB SAMUDERA JAYA",
    "pemohon": "PT. MARITIM SAMUDERA",
    "docType": "PDS",
    "isSps": false,
    "isPds": true,
    "perihal": "DINAS SURVEY KLAS",
    "jenisSurvey": "Docking Survey",
    "petugas": "SANDI NANDARIANTO",
    "pangkat": "GRADE 5 C",
    "jabatan": "SURVEYOR",
    "tempatSurvey": "BATAM",
    "lokasi": "BATAM",
    "tglMulai": "2026-08-05",
    "tglSelesai": "2026-08-09",
    "saranaTransportasi": "UDARA DAN DARAT",
    "kategoriTransportasi": "Pesawat Terbang",
    "kategoriPerjalanan": "Luar Kota",
    "status": "Selesai",
    "approvalStatus": "ACC",
    "approvalDate": "2026-08-09T14:00:00+00:00",
    "approvedBy": "MUHSON NURROCHMAT",
    "tarifDasar": 4500000,
    "uangHarian": 0,
    "biayaTiket": 3300000,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "jumlahEstimasi": 7800000,
    "isCito": true,
    "catatan": "Docking Survey TB Samudera Jaya di Batam dengan surcharge CITO.",
    "shipsList": [],
    "shipsDetail": [],
    "isParafSent": false
  },
  {
    "id": "ST-BKI-2026-003",
    "nomor": "A 0    /SV.247/PK/KI-26",
    "noAgenda": "003/2026",
    "agenda": "003/2026",
    "namaKapal": "MV NUSANTARA EXPRESS",
    "pemohon": "PT. EXPRESS LOGISTIK",
    "docType": "PDS",
    "isSps": false,
    "isPds": true,
    "perihal": "DINAS SURVEY KLAS",
    "jenisSurvey": "Intermediate",
    "petugas": "ANDRE GUNTUR",
    "pangkat": "GRADE 6 A",
    "jabatan": "SURVEYOR",
    "tempatSurvey": "JAKARTA",
    "lokasi": "JAKARTA",
    "tglMulai": "2026-08-15",
    "tglSelesai": "2026-08-20",
    "saranaTransportasi": "UDARA DAN DARAT",
    "kategoriTransportasi": "Pesawat Terbang",
    "kategoriPerjalanan": "Luar Kota",
    "status": "Berjalan",
    "approvalStatus": "Menunggu ACC",
    "approvalDate": null,
    "approvedBy": null,
    "tarifDasar": 3500000,
    "uangHarian": 0,
    "biayaTiket": 2400000,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "jumlahEstimasi": 5900000,
    "isCito": false,
    "catatan": "Intermediate Survey MV Nusantara Express di Jakarta.",
    "shipsList": [],
    "shipsDetail": [],
    "isParafSent": false
  },
  {
    "id": "SPS-2026-001",
    "nomor": null,
    "noAgenda": "004/2026",
    "agenda": "004/2026",
    "namaKapal": "KM PELITA MARITIM",
    "pemohon": "PT. PELITA BAHARI",
    "docType": "SPS",
    "isSps": true,
    "isPds": false,
    "perihal": "DINAS SURVEY KLAS",
    "jenisSurvey": "Renewal Survey",
    "petugas": "SEPTIAN AJI DEWANGKARA",
    "pangkat": "GRADE 5 C",
    "jabatan": "SURVEYOR",
    "tempatSurvey": "SURABAYA",
    "lokasi": "SURABAYA",
    "tglMulai": "2026-08-22",
    "tglSelesai": "2026-08-25",
    "saranaTransportasi": "",
    "kategoriTransportasi": "",
    "kategoriPerjalanan": "",
    "status": "Menunggu Survei",
    "approvalStatus": "Menunggu ACC",
    "approvalDate": null,
    "approvedBy": null,
    "tarifDasar": 0,
    "uangHarian": 0,
    "biayaTiket": 0,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "jumlahEstimasi": 0,
    "isCito": false,
    "catatan": "",
    "shipsList": [
      {
        "noAgenda": "004/2026",
        "namaKapal": "KM PELITA MARITIM"
      }
    ],
    "shipsDetail": [],
    "isParafSent": true
  },
  {
    "id": "SPS-2026-002",
    "nomor": null,
    "noAgenda": "005/2026",
    "agenda": "005/2026",
    "namaKapal": "TB KARTIKA 05",
    "pemohon": "PT. KARTIKA SAMUDRA",
    "docType": "SPS",
    "isSps": true,
    "isPds": false,
    "perihal": "DINAS SURVEY KLAS",
    "jenisSurvey": "Annual Survey",
    "petugas": "ALFIAN BONE PUTRA",
    "pangkat": "GRADE 6 A",
    "jabatan": "SURVEYOR",
    "tempatSurvey": "PONTIANAK",
    "lokasi": "PONTIANAK",
    "tglMulai": "2026-08-25",
    "tglSelesai": "2026-08-28",
    "saranaTransportasi": "",
    "kategoriTransportasi": "",
    "kategoriPerjalanan": "",
    "status": "Menunggu Survei",
    "approvalStatus": "Menunggu ACC",
    "approvalDate": null,
    "approvedBy": null,
    "tarifDasar": 0,
    "uangHarian": 0,
    "biayaTiket": 0,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "jumlahEstimasi": 0,
    "isCito": false,
    "catatan": "",
    "shipsList": [
      {
        "noAgenda": "005/2026",
        "namaKapal": "TB KARTIKA 05"
      }
    ],
    "shipsDetail": [],
    "isParafSent": false
  }
];

export const INITIAL_KWITANSI_HONOR = [
  {
    "id": "KW-BKI-2026-001",
    "suratId": "ST-BKI-2026-001",
    "nomorSurat": "A 0    /SV.245/PK/KI-26",
    "namaKapal": "KM MUTIARA LAUT",
    "penerima": "ALFIAN BONE PUTRA",
    "lokasi": "PONTIANAK",
    "tarifDasar": 3000000,
    "biayaTiket": 0,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 0,
    "kategoriTransportasi": "Kendaraan Operasional",
    "jumlah": 3000000,
    "status": "Sudah Dibayar",
    "tglBayar": "2026-08-04",
    "catatan": "Honorarium Annual Survey KM Mutiara Laut Pontianak"
  },
  {
    "id": "KW-BKI-2026-002",
    "suratId": "ST-BKI-2026-002",
    "nomorSurat": "A 0    /SV.246/PK/KI-26",
    "namaKapal": "TB SAMUDERA JAYA",
    "penerima": "SANDI NANDARIANTO",
    "lokasi": "BATAM",
    "tarifDasar": 4500000,
    "biayaTiket": 3300000,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 3300000,
    "kategoriTransportasi": "Pesawat Terbang",
    "jumlah": 7800000,
    "status": "Belum Dibayar",
    "tglBayar": "",
    "catatan": "Honorarium Docking Survey CITO (+50%) + Reimbursment Tiket Batam"
  },
  {
    "id": "KW-BKI-2026-003",
    "suratId": "ST-BKI-2026-003",
    "nomorSurat": "A 0    /SV.247/PK/KI-26",
    "namaKapal": "MV NUSANTARA EXPRESS",
    "penerima": "ANDRE GUNTUR",
    "lokasi": "JAKARTA",
    "tarifDasar": 3500000,
    "biayaTiket": 2400000,
    "tiketHotel": 0,
    "tiketPesawatTaxi": 2400000,
    "kategoriTransportasi": "Pesawat Terbang",
    "jumlah": 5900000,
    "status": "Belum Dibayar",
    "tglBayar": "",
    "catatan": "Honorarium Intermediate Survey + Reimbursment Tiket Jakarta"
  }
];

export const INITIAL_LAPORAN_SURVEI = [
  {
    "id": "LAP-BKI-2026-001",
    "suratId": "ST-BKI-2026-001",
    "namaKapal": "KM MUTIARA LAUT",
    "petugas": "ALFIAN BONE PUTRA",
    "lokasi": "PONTIANAK",
    "lokasiSurvey": "PONTIANAK",
    "namaSurvey": "Annual Survey",
    "tglLapor": "2026-08-03",
    "tanggal": "2026-08-03",
    "nilai": 3000000,
    "tarifDasar": 3000000,
    "isCito": false,
    "hasil": "Pemeriksaan tahunan lambung dan permesinan KM MUTIARA LAUT sesuai standar BKI. Rekomendasi perpanjangan sertifikat klas disetujui.",
    "status": "Disetujui"
  },
  {
    "id": "LAP-BKI-2026-002",
    "suratId": "ST-BKI-2026-002",
    "namaKapal": "TB SAMUDERA JAYA",
    "petugas": "SANDI NANDARIANTO",
    "lokasi": "BATAM",
    "lokasiSurvey": "BATAM",
    "namaSurvey": "Docking Survey",
    "tglLapor": "2026-08-10",
    "tanggal": "2026-08-10",
    "nilai": 4500000,
    "tarifDasar": 4500000,
    "isCito": true,
    "hasil": "[⚡ CITO] Pelaksanaan survei docking dan pemeriksaan poros baling-baling TB SAMUDERA JAYA di Galangan Batam selesai dilaksanakan dengan baik.",
    "status": "Terkirim"
  }
];
