export const INITIAL_SURAT_TUGAS = [
  {
    id: 'ST-BKI-2026-001',
    nomor: 'A 0    /SV.201/PK/KI-26',
    namaKapal: 'KAPUAS BAHARI XXII',
    perihal: 'DINAS SURVEY KLAS',
    petugas: 'ALFIAN BONE PUTRA',
    pangkat: 'GRADE 6 A',
    jabatan: 'SURVEYOR',
    lokasi: 'KENDAWANGAN',
    tarifDasar: 3500000,
    isCito: true,
    biayaTiket: 1250000,
    kategoriTransportasi: 'Pesawat Terbang',
    saranaTransportasi: 'UDARA, DARAT DAN AIR',
    keteranganLain: 'BIAYA DITANGGUNG SEPENUHNYA OLEH PT.BIRO KLASIFIKASI INDONESIA (Persero) CAB.MADYA KLAS PONTIANAK',
    kepalaCabang: 'MUHSON NURROCHMAT',
    nup: '48199-KI',
    fileTiketName: 'Tiket_Garuda_Budi.pdf',
    tglMulai: '2026-06-20',
    tglSelesai: '2026-06-21',
    status: 'Selesai',
    catatan: 'Survei CITO hari libur nasional. Ultrasonic thickness testing pelat lambung BKI.'
  },
  {
    id: 'ST-BKI-2026-002',
    nomor: 'A 0    /SV.202/PK/KI-26',
    namaKapal: 'BG EQUATORIAL 300',
    perihal: 'INSPEKSI KETEBALAN PELAT & LOAD LINE',
    petugas: 'SITI RAHMAWATI',
    pangkat: 'GRADE 5 B',
    jabatan: 'MARINE ENGINEER',
    lokasi: 'PONTIANAK',
    tarifDasar: 3200000,
    isCito: false,
    biayaTiket: 0,
    kategoriTransportasi: 'Travel / Mobil Dinas',
    saranaTransportasi: 'DARAT DAN AIR',
    keteranganLain: 'BIAYA DITANGGUNG SEPENUHNYA OLEH PT.BIRO KLASIFIKASI INDONESIA (Persero) CAB.MADYA KLAS PONTIANAK',
    kepalaCabang: 'MUHSON NURROCHMAT',
    nup: '48199-KI',
    fileTiketName: '',
    tglMulai: '2026-10-08',
    tglSelesai: '2026-10-14',
    status: 'Berjalan',
    catatan: 'Pengujian ketebalan pelat geladak & sertifikasi batas muat air tawar Kapuas.'
  },
  {
    id: 'ST-BKI-2026-003',
    nomor: 'A 0    /SV.203/PK/KI-26',
    namaKapal: 'KM KHATULISTIWA EXPRESS',
    perihal: 'SURVEI PERIODIK KESELAMATAN KAPAL',
    petugas: 'AHMAD FAUZI',
    pangkat: 'GRADE 6 B',
    jabatan: 'HULL INSPECTOR',
    lokasi: 'MEMPAWAH',
    tarifDasar: 4000000,
    isCito: true,
    biayaTiket: 750000,
    kategoriTransportasi: 'Travel / Mobil Dinas',
    saranaTransportasi: 'UDARA DAN DARAT',
    keteranganLain: 'BIAYA DITANGGUNG SEPENUHNYA OLEH PT.BIRO KLASIFIKASI INDONESIA (Persero) CAB.MADYA KLAS PONTIANAK',
    kepalaCabang: 'MUHSON NURROCHMAT',
    nup: '48199-KI',
    fileTiketName: 'Bukti_Travel_Ahmad.pdf',
    tglMulai: '2026-10-12',
    tglSelesai: '2026-10-18',
    status: 'Berjalan',
    catatan: 'Pekerjaan CITO persiapan sertifikat kelaiklautan pelayaran penumpang Kijing.'
  },
  {
    id: 'ST-BKI-2026-004',
    nomor: 'A 0    /SV.204/PK/KI-26',
    namaKapal: 'MT BORNEAN PIONEER 02',
    perihal: 'SURVEI KLASIFIKASI ANTARA & MARPOL',
    petugas: 'DEWI LESTARI',
    pangkat: 'GRADE 7 A',
    jabatan: 'NAVCOM SURVEYOR',
    lokasi: 'SAMBAS',
    tarifDasar: 4200000,
    isCito: false,
    biayaTiket: 1500000,
    kategoriTransportasi: 'Pesawat Terbang',
    saranaTransportasi: 'UDARA, DARAT DAN AIR',
    keteranganLain: 'BIAYA DITANGGUNG SEPENUHNYA OLEH PT.BIRO KLASIFIKASI INDONESIA (Persero) CAB.MADYA KLAS PONTIANAK',
    kepalaCabang: 'MUHSON NURROCHMAT',
    nup: '48199-KI',
    fileTiketName: 'Tiket_Wings_Dewi.pdf',
    tglMulai: '2026-10-20',
    tglSelesai: '2026-10-25',
    status: 'Belum Mulai',
    catatan: 'Pemeriksaan sistem pemisah air dan minyak (OWS) & peralatan radio GMDSS.'
  }
];

export const INITIAL_KWITANSI_HONOR = [
  {
    id: 'KW-BKI-2026-001',
    suratId: 'ST-BKI-2026-001',
    penerima: 'Budi Santoso, ST (Senior Class Surveyor)',
    tarifDasar: 3500000,
    isCito: true,
    biayaTiket: 1250000,
    kategoriTransportasi: 'Pesawat Terbang',
    fileTiketName: 'Tiket_Garuda_Budi.pdf',
    jumlah: 6500000, // 3.5M + 1.75M (CITO 50%) + 1.25M (Tiket) = 6.5M
    tglBayar: '2026-10-06',
    status: 'Sudah Dibayar',
    catatan: 'Honorarium CITO BKI Pontianak (+50%) + Reimbursment Tiket Pesawat Garuda'
  },
  {
    id: 'KW-BKI-2026-002',
    suratId: 'ST-BKI-2026-002',
    penerima: 'Siti Rahmawati, ST (Marine Engineer)',
    tarifDasar: 3200000,
    isCito: false,
    biayaTiket: 0,
    kategoriTransportasi: 'Travel / Mobil Dinas',
    jumlah: 3200000,
    tglBayar: '2026-10-15',
    status: 'Belum Dibayar',
    catatan: 'Honorarium Survei BKI Tongkang BG Equatorial 300 di Kapuas'
  },
  {
    id: 'KW-BKI-2026-003',
    suratId: 'ST-BKI-2026-003',
    penerima: 'Ahmad Fauzi, ST (Hull Inspector)',
    tarifDasar: 4000000,
    isCito: true,
    biayaTiket: 750000,
    kategoriTransportasi: 'Travel / Mobil Dinas',
    jumlah: 6750000, // 4M + 2M (CITO 50%) + 750k (Tiket) = 6.75M
    tglBayar: '2026-10-20',
    status: 'Belum Dibayar',
    catatan: 'Honorarium CITO Pelabuhan Kijing (+50%) + Transport Travel Mempawah'
  }
];

export const INITIAL_LAPORAN_SURVEI = [
  {
    id: 'LAP-BKI-2026-001',
    suratId: 'ST-BKI-2026-001',
    namaKapal: 'TB Kapuas Indah 08',
    petugas: 'Budi Santoso, ST (Senior Class Surveyor)',
    tglLapor: '2026-10-06',
    isCito: true,
    biayaTiket: 1250000,
    hasil: '[⚡ CITO / Hari Libur (+50%)] [🎟️ Tiket Pesawat: Rp 1.250.000] Hasil ultrasonik tes pelat lambung TB Kapuas Indah 08 sesuai standar klasifikasi BKI. Sertifikat pembaruan kelas diterbitkan.',
    status: 'Disetujui'
  },
  {
    id: 'LAP-BKI-2026-002',
    suratId: 'ST-BKI-2026-002',
    namaKapal: 'BG Equatorial 300',
    petugas: 'Siti Rahmawati, ST (Marine Engineer)',
    tglLapor: '2026-10-11',
    isCito: false,
    biayaTiket: 0,
    hasil: '[Standar BKI] Pengujian kekedapan sekat kompartemen ganda tongkang BG Equatorial 300 di Galangan Kapuas memenuhi rekomendasi keselamatan.',
    status: 'Terkirim'
  },
  {
    id: 'LAP-BKI-2026-003',
    suratId: 'ST-BKI-2026-003',
    namaKapal: 'KM Khatulistiwa Express',
    petugas: 'Ahmad Fauzi, ST (Hull Inspector)',
    tglLapor: '2026-10-11',
    isCito: true,
    biayaTiket: 750000,
    hasil: '[⚡ CITO / Hari Libur (+50%)] Draf rekomendasi perbaikan alat keselamatan pelampung dan rakit penolong terluap (ILR) kapal penumpang Kijing.',
    status: 'Draf'
  }
];
